### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by viveknuna** [IVSoftware/key_filter_for_console#1]
I am getting the below error on building solution in Visual Studio 2019.

![image](https://user-images.githubusercontent.com/3524495/180591846-5dfcc47d-1298-4bb9-8a15-3f94f1aabc2d.png)

**Comment by viveknuna** [comment]
@IVSoftware please remove these lines from csproj file, It will fix this issue.

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>C:\Users\Tom Gregor\source\repos\key_filter_for_console\key_filter_for_console\NoteEditor\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>C:\Users\Tom Gregor\source\repos\key_filter_for_console\key_filter_for_console\NoteEditor\</OutputPath>
  </PropertyGroup>
```

**Comment by IVSoftware** [comment]
Thanks for bringing this to my attention. Will look into it tomorrow. Looks like that should be a relative path.

**Comment by IVSoftware** [comment]
You probably already figured out that the point of that reference is that we end up with an up-to-date `NoteEditor` file structure in the executable path for the Console app.  In production, the installer package would take care of that. Here, the sequence is supposed to be that the build of `NoteEditor` stages it in the folder of the main project, and then those files are set to `Copy to OutputDirectory=Copy Always` to complete the process when the `key_filter_for_console` builds. Apologies for the build failure let me know if anything else comes up. My expectation is that changing the link to relative should fix the issue.

**Comment by IVSoftware** [comment]
Closing the issue. Please reopen the issue persists on your end.
